<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">execute</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgQml6
RG9jRW52ZWxvcGUgYml6ZG9jID0gQml6RG9jRW52ZWxvcGVIZWxwZXIubm9ybWFsaXplKElEYXRh
SGVscGVyLmdldChjdXJzb3IsICIkYml6ZG9jIiwgSURhdGEuY2xhc3MpLCB0cnVlKTsKICAgIFJv
dXRpbmdSdWxlIHJ1bGUgPSBSb3V0aW5nUnVsZUhlbHBlci5ub3JtYWxpemUoSURhdGFIZWxwZXIu
Z2V0KGN1cnNvciwgIiRydWxlIiwgSURhdGEuY2xhc3MpKTsKICAgIElEYXRhIHBhcmFtZXRlcnMg
PSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiVE5fcGFybXMiLCBJRGF0YS5jbGFzcyk7CgogICAg
Um91dGluZ1J1bGVIZWxwZXIuZXhlY3V0ZShydWxlLCBiaXpkb2MsIHBhcmFtZXRlcnMpOwoKICAg
IGlmIChiaXpkb2MgIT0gbnVsbCkgewogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIk
Yml6ZG9jIiwgYml6ZG9jKTsKICAgICAgICBQcm9maWxlQ2FjaGUgY2FjaGUgPSBQcm9maWxlQ2Fj
aGUuZ2V0SW5zdGFuY2UoKTsKICAgICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHNlbmRl
ciIsIGNhY2hlLmdldChiaXpkb2MuZ2V0U2VuZGVySWQoKSkpOwogICAgICAgIElEYXRhSGVscGVy
LnB1dChjdXJzb3IsICIkcmVjZWl2ZXIiLCBjYWNoZS5nZXQoYml6ZG9jLmdldFJlY2VpdmVySWQo
KSkpOwogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkcnVsZSIsIHJ1bGUpOwogICAg
fQp9IGZpbmFsbHkgewogICAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
