<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIGlkID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRpZCIsIFN0cmluZy5jbGFzcyk7CiAg
ICBib29sZWFuIGNvbnRlbnQgPSBJRGF0YUhlbHBlci5nZXRPckRlZmF1bHQoY3Vyc29yLCAiJGNv
bnRlbnQ/IiwgQm9vbGVhbi5jbGFzcywgZmFsc2UpOwogICAgYm9vbGVhbiByZWxhdGlvbnNoaXBz
ID0gSURhdGFIZWxwZXIuZ2V0T3JEZWZhdWx0KGN1cnNvciwgIiRyZWxhdGlvbnNoaXBzPyIsIEJv
b2xlYW4uY2xhc3MsIGZhbHNlKTsKICAgIGJvb2xlYW4gcmFpc2UgPSBJRGF0YUhlbHBlci5nZXRP
ckRlZmF1bHQoY3Vyc29yLCAiJHJhaXNlPyIsIEJvb2xlYW4uY2xhc3MsIGZhbHNlKTsKCiAgICBC
aXpEb2NFbnZlbG9wZSBiaXpkb2MgPSBCaXpEb2NFbnZlbG9wZUhlbHBlci5nZXQoaWQsIGNvbnRl
bnQsIHJlbGF0aW9uc2hpcHMpOwoKICAgIGlmIChiaXpkb2MgPT0gbnVsbCkgewogICAgICAgIGlm
IChyYWlzZSkgdGhyb3cgbmV3IFVucmVjb3ZlcmFibGVFeGNlcHRpb24oIlRyYWRpbmcgTmV0d29y
a3MgZG9jdW1lbnQgZG9lcyBub3QgZXhpc3Q6ICIgKyBpZCk7CiAgICB9IGVsc2UgewogICAgICAg
IElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkYml6ZG9jIiwgYml6ZG9jKTsKICAgICAgICBQcm9m
aWxlQ2FjaGUgY2FjaGUgPSBQcm9maWxlQ2FjaGUuZ2V0SW5zdGFuY2UoKTsKICAgICAgICBJRGF0
YUhlbHBlci5wdXQoY3Vyc29yLCAiJHNlbmRlciIsIGNhY2hlLmdldChiaXpkb2MuZ2V0U2VuZGVy
SWQoKSkpOwogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkcmVjZWl2ZXIiLCBjYWNo
ZS5nZXQoYml6ZG9jLmdldFJlY2VpdmVySWQoKSkpOwogICAgfQp9IGZpbmFsbHkgewogICAgY3Vy
c29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
