<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIGlkID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRpZCIsIFN0cmluZy5jbGFzcyk7CiAg
ICBib29sZWFuIGNvbnRlbnQgPSBJRGF0YUhlbHBlci5nZXRPckRlZmF1bHQoY3Vyc29yLCAiJGNv
bnRlbnQ/IiwgQm9vbGVhbi5jbGFzcywgZmFsc2UpOwogICAgYm9vbGVhbiByYWlzZSA9IElEYXRh
SGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkcmFpc2U/IiwgQm9vbGVhbi5jbGFzcywgZmFs
c2UpOwoKICAgIEJpekRvY0VudmVsb3BlIGJpemRvYyA9IEJpekRvY0VudmVsb3BlSGVscGVyLmdl
dChpZCwgY29udGVudCk7CgogICAgaWYgKGJpemRvYyA9PSBudWxsKSB7CiAgICAgICAgaWYgKHJh
aXNlKSB0aHJvdyBuZXcgVW5yZWNvdmVyYWJsZUV4Y2VwdGlvbigiVHJhZGluZyBOZXR3b3JrcyBk
b2N1bWVudCBkb2VzIG5vdCBleGlzdDogIiArIGlkKTsKICAgIH0gZWxzZSB7CiAgICAgICAgSURh
dGFIZWxwZXIucHV0KGN1cnNvciwgIiRiaXpkb2MiLCBiaXpkb2MpOwogICAgICAgIFByb2ZpbGVD
YWNoZSBjYWNoZSA9IFByb2ZpbGVDYWNoZS5nZXRJbnN0YW5jZSgpOwogICAgICAgIElEYXRhSGVs
cGVyLnB1dChjdXJzb3IsICIkc2VuZGVyIiwgY2FjaGUuZ2V0KGJpemRvYy5nZXRTZW5kZXJJZCgp
KSk7CiAgICAgICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRyZWNlaXZlciIsIGNhY2hlLmdl
dChiaXpkb2MuZ2V0UmVjZWl2ZXJJZCgpKSk7CiAgICB9Cn0gZmluYWxseSB7CiAgICBjdXJzb3Iu
ZGVzdHJveSgpOwp9</value>
</Values>
