<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">status</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgRGVm
ZXJyZXIgZGVmZXJyZXIgPSBEZWZlcnJlci5nZXRJbnN0YW5jZSgpOwoKICAgIGJvb2xlYW4gc3Rh
cnRlZCA9IGRlZmVycmVyLmlzU3RhcnRlZCgpOwoKICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3Is
ICIkYml6ZG9jLmRlZmVyLnN0YXJ0ZWQ/Iiwgc3RhcnRlZCk7CiAgICBJRGF0YUhlbHBlci5wdXQo
Y3Vyc29yLCAiJGJpemRvYy5kZWZlci5jb25jdXJyZW5jeSIsIGRlZmVycmVyLmdldENvbmN1cnJl
bmN5KCkpOwogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRiaXpkb2MuZGVmZXIuY2FwYWNp
dHkiLCBkZWZlcnJlci5nZXRDYXBhY2l0eSgpKTsKCiAgICBpZiAoc3RhcnRlZCkgewogICAgICAg
IElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkYml6ZG9jLmRlZmVyLmlkbGU/IiwgZGVmZXJyZXIu
aXNJZGxlKCkpOwogICAgICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkYml6ZG9jLmRlZmVy
LnNhdHVyYXRlZD8iLCBkZWZlcnJlci5pc1NhdHVyYXRlZCgpKTsKICAgICAgICBJRGF0YUhlbHBl
ci5wdXQoY3Vyc29yLCAiJGJpemRvYy5kZWZlci5wZW5kaW5nIiwgZGVmZXJyZXIuc2l6ZSgpKTsK
ICAgIH0KfSBmaW5hbGx5IHsKICAgIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
