<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">each</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBxdWV1ZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAicXVldWUiKTsKICBTdHJpbmcg
c2VydmljZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJHNlcnZpY2UiKTsKICBJRGF0
YSBzY29wZSA9IElEYXRhVXRpbC5nZXRJRGF0YShjdXJzb3IsICIkcGlwZWxpbmUiKTsKICBTdHJp
bmcgcyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGNvbmN1cnJlbmN5Iik7CgogIGlu
dCBjb25jdXJyZW5jeSA9IDE7CiAgaWYgKHMgIT0gbnVsbCkgY29uY3VycmVuY3kgPSBJbnRlZ2Vy
LnBhcnNlSW50KHMpOwoKICBlYWNoKHF1ZXVlLCBzZXJ2aWNlLCBzY29wZSwgY29uY3VycmVuY3kp
Owp9IGZpbmFsbHkgewogIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
