<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIGlkID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRpZCIsIFN0cmluZy5jbGFzcyk7CiAg
ICBTdHJpbmcgdHlwZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkdHlwZSIsIFN0cmluZy5j
bGFzcyk7CiAgICBib29sZWFuIHJlZnJlc2ggPSBJRGF0YUhlbHBlci5nZXRPckRlZmF1bHQoY3Vy
c29yLCAiJHJlZnJlc2g/IiwgQm9vbGVhbi5jbGFzcywgZmFsc2UpOwoKICAgIGlmIChpZCAhPSBu
dWxsKSB7CiAgICAgICAgSURhdGEgcHJvZmlsZSA9IFByb2ZpbGVDYWNoZS5nZXRJbnN0YW5jZSgp
LmdldChpZCwgdHlwZSwgcmVmcmVzaCk7CiAgICAgICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwg
IiRwcm9maWxlIiwgcHJvZmlsZSwgZmFsc2UpOwogICAgfQp9IGZpbmFsbHkgewogICAgY3Vyc29y
LmRlc3Ryb3koKTsKfQ==</value>
</Values>
