<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIFN0cmlu
ZyBpZCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiJGlkIik7CiAgU3RyaW5nIHR5cGUg
PSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiR0eXBlIik7CgogIGlmIChpZCAhPSBudWxs
KSB7CiAgICBJRGF0YSBwcm9maWxlID0gdHVuZHJhLnRuLnN1cHBvcnQucHJvZmlsZS5nZXQoaWQs
IHR5cGUpOwogICAgaWYgKHByb2ZpbGUgIT0gbnVsbCkgSURhdGFVdGlsLnB1dChjdXJzb3IsICIk
cHJvZmlsZSIsIHByb2ZpbGUpOwogIH0KfSBjYXRjaCAoamF2YS5pby5JT0V4Y2VwdGlvbiBleCkg
ewogIHR1bmRyYS50bi5zdXBwb3J0LnByb2ZpbGUucmFpc2UoZXgpOwp9IGZpbmFsbHkgewogIGN1
cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
