<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIGlkID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkaWQiKTsKICAgIFN0cmluZyBu
YW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkbmFtZSIpOwoKICAgIEJpekRvY1R5
cGUgdHlwZSA9IG51bGw7CgogICAgaWYgKGlkICE9IG51bGwpIHsKICAgICAgICB0eXBlID0gQml6
RG9jVHlwZUhlbHBlci5nZXQoaWQpOwogICAgfSBlbHNlIGlmIChuYW1lICE9IG51bGwpIHsKICAg
ICAgICB0eXBlID0gQml6RG9jVHlwZUhlbHBlci5nZXRCeU5hbWUobmFtZSk7CiAgICB9CgogICAg
aWYgKHR5cGUgIT0gbnVsbCkgewogICAgICAgIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJHR5cGUi
LCBJRGF0YUhlbHBlci5ub3JtYWxpemUodHlwZS5nZXRJRGF0YSgpKSk7CiAgICB9Cn0gZmluYWxs
eSB7CiAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
