<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIGlkID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRpZCIsIFN0cmluZy5jbGFzcyk7CiAg
ICBTdHJpbmcgbmFtZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkbmFtZSIsIFN0cmluZy5j
bGFzcyk7CgogICAgQml6RG9jVHlwZSB0eXBlID0gbnVsbDsKCiAgICBpZiAoaWQgIT0gbnVsbCkg
ewogICAgICAgIHR5cGUgPSBCaXpEb2NUeXBlSGVscGVyLmdldChpZCk7CiAgICB9IGVsc2UgaWYg
KG5hbWUgIT0gbnVsbCkgewogICAgICAgIHR5cGUgPSBCaXpEb2NUeXBlSGVscGVyLmdldEJ5TmFt
ZShuYW1lKTsKICAgIH0KCiAgICBpZiAodHlwZSAhPSBudWxsKSB7CiAgICAgICAgSURhdGFIZWxw
ZXIucHV0KGN1cnNvciwgIiR0eXBlIiwgSURhdGFIZWxwZXIubm9ybWFsaXplKChJRGF0YSl0eXBl
KSk7CiAgICB9Cn0gZmluYWxseSB7CiAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
