<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">route</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgQml6
RG9jRW52ZWxvcGUgYml6ZG9jID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgImJpemRvYyIsIEJp
ekRvY0VudmVsb3BlLmNsYXNzKTsKICAgIFJvdXRpbmdSdWxlIHJ1bGUgPSBJRGF0YUhlbHBlci5n
ZXQoY3Vyc29yLCAicnVsZSIsIFJvdXRpbmdSdWxlLmNsYXNzKTsKICAgIElEYXRhIHBhcmFtZXRl
cnMgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiVE5fcGFybXMiLCBJRGF0YS5jbGFzcyk7Cgog
ICAgRGVmZXJyZXIuZ2V0SW5zdGFuY2UoKS5kZWZlcihuZXcgQ2FsbGFibGVSb3V0ZShiaXpkb2Ms
IHJ1bGUsIHBhcmFtZXRlcnMpKTsKfSBjYXRjaChFeGNlcHRpb24gZXgpIHsKICAgIEV4Y2VwdGlv
bkhlbHBlci5yYWlzZShleCk7Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
