<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">length</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIHF1ZXVlTmFtZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkcXVldWUiLCBTdHJpbmcu
Y2xhc3MpOwogICAgSURhdGFIZWxwZXIucHV0KGN1cnNvciwgIiRsZW5ndGgiLCBEZWxpdmVyeVF1
ZXVlSGVscGVyLmxlbmd0aChEZWxpdmVyeVF1ZXVlSGVscGVyLmdldChxdWV1ZU5hbWUpKSwgU3Ry
aW5nLmNsYXNzKTsKfSBjYXRjaChJT0V4Y2VwdGlvbiBleCkgewogICAgRXhjZXB0aW9uSGVscGVy
LnJhaXNlKGV4KTsKfSBjYXRjaChTUUxFeGNlcHRpb24gZXgpIHsKICAgIEV4Y2VwdGlvbkhlbHBl
ci5yYWlzZShleCk7Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
