<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">exists</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgYml6ZG9jID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRiaXpkb2MiLCBJRGF0YS5jbGFz
cyk7CiAgICBJRGF0YSBjbGFzc2VzID0gSURhdGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRjbGFzcyIs
IElEYXRhLmNsYXNzKTsKCiAgICBBY3Rpdml0eUxvZ0VudHJ5W10gZXJyb3JzID0gQml6RG9jRW52
ZWxvcGVIZWxwZXIuZ2V0RXJyb3JzKGJpemRvYywgY2xhc3Nlcyk7CgogICAgSURhdGFIZWxwZXIu
cHV0KGN1cnNvciwgIiRleGlzdHM/IiwgZXJyb3JzICE9IG51bGwgJiYgZXJyb3JzLmxlbmd0aCA+
IDAsIFN0cmluZy5jbGFzcyk7CiAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJGVycm9ycyIs
IElEYXRhSGVscGVyLm5vcm1hbGl6ZShlcnJvcnMpLCBmYWxzZSk7Cn0gZmluYWxseSB7CiAgICBj
dXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
