<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogIElEYXRh
IGJpemRvYyA9IElEYXRhVXRpbC5nZXRJRGF0YShjdXJzb3IsICIkYml6ZG9jIik7CiAgU3RyaW5n
IHBhcnROYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICIkcGFydCIpOwoKICBpZiAo
Yml6ZG9jICE9IG51bGwpIHsKICAgIENvbnRlbnRQYXJ0IHBhcnQgPSBuZXcgQ29udGVudFBhcnQo
Yml6ZG9jLCBwYXJ0TmFtZSk7CiAgICBqYXZhLmlvLklucHV0U3RyZWFtIGNvbnRlbnQgPSBwYXJ0
LmdldENvbnRlbnQoKTsKCiAgICBpZiAoY29udGVudCAhPSBudWxsKSB7CiAgICAgIElEYXRhVXRp
bC5wdXQoY3Vyc29yLCAiJGNvbnRlbnQiLCBjb250ZW50KTsKICAgICAgSURhdGFVdGlsLnB1dChj
dXJzb3IsICIkY29udGVudC50eXBlIiwgcGFydC5nZXRNaW1lVHlwZSgpKTsKICAgIH0KICB9Cn0g
ZmluYWxseSB7CiAgY3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
