<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">relate</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgQml6
RG9jRW52ZWxvcGUgc291cmNlID0gQml6RG9jRW52ZWxvcGVIZWxwZXIubm9ybWFsaXplKElEYXRh
SGVscGVyLmdldChjdXJzb3IsICIkYml6ZG9jLnNvdXJjZSIsIElEYXRhLmNsYXNzKSwgZmFsc2Us
IGZhbHNlKTsKICAgIEJpekRvY0VudmVsb3BlIHRhcmdldCA9IEJpekRvY0VudmVsb3BlSGVscGVy
Lm5vcm1hbGl6ZShJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGJpemRvYy50YXJnZXQiLCBJRGF0
YS5jbGFzcyksIGZhbHNlLCBmYWxzZSk7CiAgICBTdHJpbmcgcmVsYXRpb25zaGlwID0gSURhdGFI
ZWxwZXIuZ2V0KGN1cnNvciwgIiRyZWxhdGlvbnNoaXAiLCBTdHJpbmcuY2xhc3MpOwoKICAgIEJp
ekRvY0VudmVsb3BlSGVscGVyLnJlbGF0ZShzb3VyY2UsIHRhcmdldCwgcmVsYXRpb25zaGlwKTsK
fSBmaW5hbGx5IHsKICAgIGN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
