<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">enqueue</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgQml6
RG9jRW52ZWxvcGUgZG9jdW1lbnQgPSBCaXpEb2NFbnZlbG9wZUhlbHBlci5ub3JtYWxpemUoSURh
dGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRiaXpkb2MiLCBJRGF0YS5jbGFzcyksIGZhbHNlLCBmYWxz
ZSk7CiAgICBEZWxpdmVyeVF1ZXVlIHF1ZXVlID0gRGVsaXZlcnlRdWV1ZUhlbHBlci5nZXQoSURh
dGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRxdWV1ZSIsIFN0cmluZy5jbGFzcykpOwogICAgYm9vbGVh
biBmb3JjZSA9IElEYXRhSGVscGVyLmdldE9yRGVmYXVsdChjdXJzb3IsICIkZm9yY2U/IiwgQm9v
bGVhbi5jbGFzcywgZmFsc2UpOwogICAgU3RyaW5nIHN1bW1hcnkgPSBJRGF0YUhlbHBlci5nZXQo
Y3Vyc29yLCAiJHR1bmRyYS50bi5kb2N1bWVudC5lbnF1ZXVlLmxvZy5tZXNzYWdlLnN1bW1hcnku
cHJlZml4IiwgU3RyaW5nLmNsYXNzKTsKICAgIElEYXRhIGNvbnRleHQgPSBJRGF0YUhlbHBlci5n
ZXQoY3Vyc29yLCAiJHR1bmRyYS50bi5kb2N1bWVudC5lbnF1ZXVlLmxvZy5jb250ZXh0IiwgSURh
dGEuY2xhc3MpOwoKICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkdGFzayIsIEJpekRvY0Vu
dmVsb3BlSGVscGVyLmVucXVldWUoZG9jdW1lbnQsIHF1ZXVlLCBmb3JjZSwgc3VtbWFyeSwgY29u
dGV4dCksIGZhbHNlKTsKfSBjYXRjaChFeGNlcHRpb24gZXgpIHsKICAgIEV4Y2VwdGlvbkhlbHBl
ci5yYWlzZShleCk7Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
