<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">normalize</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSURh
dGEgaW5wdXQgPSBJRGF0YVV0aWwuZ2V0SURhdGEoY3Vyc29yLCAiJGJpemRvYyIpOwogICAgYm9v
bGVhbiBjb250ZW50ID0gQm9vbGVhbkhlbHBlci5wYXJzZShJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1
cnNvciwgIiRjb250ZW50PyIpKTsKICAgIGJvb2xlYW4gc2VuZGVyID0gQm9vbGVhbkhlbHBlci5w
YXJzZShJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgIiRzZW5kZXI/IikpOwogICAgYm9vbGVh
biByZWNlaXZlciA9IEJvb2xlYW5IZWxwZXIucGFyc2UoSURhdGFVdGlsLmdldFN0cmluZyhjdXJz
b3IsICIkcmVjZWl2ZXI/IikpOwoKICAgIEJpekRvY0VudmVsb3BlIG91dHB1dCA9IEJpekRvY0hl
bHBlci5ub3JtYWxpemUoaW5wdXQsIGNvbnRlbnQpOwoKICAgIGlmIChvdXRwdXQgIT0gbnVsbCkg
ewogICAgICAgIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiJGJpemRvYyIsIG91dHB1dCk7CiAgICAg
ICAgaWYgKHNlbmRlcikgSURhdGFVdGlsLnB1dChjdXJzb3IsICIkc2VuZGVyIiwgUHJvZmlsZUNh
Y2hlLmdldEluc3RhbmNlKCkuZ2V0KG91dHB1dC5nZXRTZW5kZXJJZCgpKSk7CiAgICAgICAgaWYg
KHJlY2VpdmVyKSBJRGF0YVV0aWwucHV0KGN1cnNvciwgIiRyZWNlaXZlciIsIFByb2ZpbGVDYWNo
ZS5nZXRJbnN0YW5jZSgpLmdldChvdXRwdXQuZ2V0UmVjZWl2ZXJJZCgpKSk7CiAgICB9Cn0gZmlu
YWxseSB7CiAgICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
