<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">start</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgSW50
ZWdlciBjb25jdXJyZW5jeSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkYml6ZG9jLmRlZmVy
LmNvbmN1cnJlbmN5IiwgSW50ZWdlci5jbGFzcyk7CiAgICBJbnRlZ2VyIGNhcGFjaXR5ID0gSURh
dGFIZWxwZXIuZ2V0KGN1cnNvciwgIiRiaXpkb2MuZGVmZXIuY2FwYWNpdHkiLCBJbnRlZ2VyLmNs
YXNzKTsKCiAgICBEZWZlcnJlciBkZWZlcnJlciA9IERlZmVycmVyLmdldEluc3RhbmNlKCk7Cgog
ICAgaWYgKGNvbmN1cnJlbmN5ICE9IG51bGwgJiYgY29uY3VycmVuY3kgPj0gMSkgZGVmZXJyZXIu
c2V0Q29uY3VycmVuY3koY29uY3VycmVuY3kpOwogICAgaWYgKGNhcGFjaXR5ICE9IG51bGwgJiYg
Y2FwYWNpdHkgPj0gMSkgZGVmZXJyZXIuc2V0Q2FwYWNpdHkoY2FwYWNpdHkpOwoKICAgIGRlZmVy
cmVyLnN0YXJ0KCk7Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
