<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">recognize</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgT2Jq
ZWN0IGNvbnRlbnQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGNvbnRlbnQiKTsKICAgIFN0
cmluZyBjb250ZW50SWRlbnRpdHkgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29yLCAiJGNvbnRlbnQu
aWRlbnRpdHkiLCBTdHJpbmcuY2xhc3MpOwogICAgSURhdGEgY29udGVudE5hbWVzcGFjZSA9IElE
YXRhSGVscGVyLmZpcnN0KGN1cnNvciwgSURhdGEuY2xhc3MsICIkY29udGVudC5uYW1lc3BhY2Ui
LCAiJG5hbWVzcGFjZSIpOwogICAgSURhdGEgcGFyYW1ldGVycyA9IElEYXRhSGVscGVyLmdldChj
dXJzb3IsICJUTl9wYXJtcyIsIElEYXRhLmNsYXNzKTsKCiAgICBCaXpEb2NFbnZlbG9wZSBiaXpk
b2MgPSBCaXpEb2NFbnZlbG9wZUhlbHBlci5yZWNvZ25pemUoY29udGVudCwgY29udGVudElkZW50
aXR5LCBjb250ZW50TmFtZXNwYWNlLCBwYXJhbWV0ZXJzKTsKCiAgICBJRGF0YUhlbHBlci5wdXQo
Y3Vyc29yLCAiJGJpemRvYyIsIGJpemRvYywgZmFsc2UpOwogICAgSURhdGFIZWxwZXIucHV0KGN1
cnNvciwgIlROX3Bhcm1zIiwgcGFyYW1ldGVycywgZmFsc2UpOwp9IGZpbmFsbHkgewogICAgY3Vy
c29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
