<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">list</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgQml6
RG9jRW52ZWxvcGUgYml6ZG9jID0gQml6RG9jRW52ZWxvcGVIZWxwZXIubm9ybWFsaXplKElEYXRh
SGVscGVyLmdldChjdXJzb3IsICIkYml6ZG9jIiwgSURhdGEuY2xhc3MpKTsKICAgIElEYXRhW10g
dGFza3MgPSBJRGF0YUhlbHBlci5ub3JtYWxpemUoR3VhcmFudGVlZEpvYkhlbHBlci5saXN0KGJp
emRvYykpOwoKICAgIGlmICh0YXNrcyAhPSBudWxsICYmIHRhc2tzLmxlbmd0aCA+IDApIHsKICAg
ICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAiJHRhc2tzIiwgdGFza3MpOwogICAgICAgIElE
YXRhSGVscGVyLnB1dChjdXJzb3IsICIkdGFza3MubGVuZ3RoIiwgdGFza3MubGVuZ3RoLCBTdHJp
bmcuY2xhc3MpOwogICAgfSBlbHNlIHsKICAgICAgICBJRGF0YUhlbHBlci5wdXQoY3Vyc29yLCAi
JHRhc2tzLmxlbmd0aCIsICIwIik7CiAgICB9Cn0gY2F0Y2goU1FMRXhjZXB0aW9uIGV4KSB7CiAg
ICBFeGNlcHRpb25IZWxwZXIucmFpc2UoZXgpOwp9IGZpbmFsbHkgewogICAgY3Vyc29yLmRlc3Ry
b3koKTsKfQ==</value>
</Values>
