<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewogICAgU3Ry
aW5nIHF1ZXVlTmFtZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkcXVldWUiLCBTdHJpbmcu
Y2xhc3MpOwoKICAgIElEYXRhIHByb3BlcnRpZXMgPSBEZWxpdmVyeVF1ZXVlSGVscGVyLnRvSURh
dGEoRGVsaXZlcnlRdWV1ZUhlbHBlci5nZXQocXVldWVOYW1lKSk7CiAgICAKICAgIElEYXRhSGVs
cGVyLnB1dChjdXJzb3IsICIkcXVldWUucHJvcGVydGllcyIsIHByb3BlcnRpZXMsIGZhbHNlKTsK
ICAgIElEYXRhSGVscGVyLnB1dChjdXJzb3IsICIkcXVldWUuZXhpc3RzPyIsIHByb3BlcnRpZXMg
IT0gbnVsbCwgU3RyaW5nLmNsYXNzKTsKfSBjYXRjaChJT0V4Y2VwdGlvbiBleCkgewogICAgRXhj
ZXB0aW9uSGVscGVyLnJhaXNlKGV4KTsKfSBjYXRjaChTUUxFeGNlcHRpb24gZXgpIHsKICAgIEV4
Y2VwdGlvbkhlbHBlci5yYWlzZShleCk7Cn0gZmluYWxseSB7CiAgICBjdXJzb3IuZGVzdHJveSgp
Owp9</value>
</Values>
